name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.5', '2.5.1', '2.5.2','2.6.1','2.6.2', '2.6.3' ,'2.7','2.7.1', '2.7.2' ,'3.0']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
    - name: CHECK IP address
      run: |
        curl ifconfig.me
        ruby -v
      
